/**
 * build-index.js
 *
 * Reads the raw Typeform export and writes two artefacts that the rest of the
 * migration depends on:
 *
 *   migration/file_index.csv  one row per uploaded file (200 rows), recording
 *                             which response and which slot each ORIGINAL
 *                             filename belongs to. This is the lookup table
 *                             that makes a dropped file self-identifying.
 *   migration/batches.md      the drop order, batch by batch.
 *
 * Neither artefact contains contact details or dates of birth. Filenames are
 * included because they are the join key.
 *
 * The raw export is never in git, so batches.md would otherwise be impossible to
 * regenerate in a fresh checkout. --from-index rebuilds it from the committed
 * file_index.csv instead, which holds everything the drop order needs.
 *
 * Usage:  SOURCE_CSV=/path/to/responses.csv node migration/scripts/build-index.js
 *         node migration/scripts/build-index.js --from-index
 */

const fs = require('fs');
const path = require('path');
const { parseCsv, toCsv } = require('./csv');
const { PATHS, COL, SLOTS, bucketForExt, POLICY } = require('./config');

const basename = (url) => (url || '').trim().split('/').pop() || '';

// The hash segment of a Typeform file URL. Unique across all 200 files, so it
// doubles as a stable identifier when a filename is ambiguous.
const typeformHash = (url) => {
  const m = (url || '').match(/\/responses\/files\/([0-9a-f]+)\//);
  return m ? m[1] : '';
};

// One row per uploaded file, read off the raw export.
const indexFromSource = () => {
  if (!fs.existsSync(PATHS.sourceCsv)) {
    console.error(`Source CSV not found at ${PATHS.sourceCsv}`);
    console.error('Pass it explicitly:  SOURCE_CSV=/path/to/responses.csv node migration/scripts/build-index.js');
    console.error('Or rebuild batches.md alone from the committed index:  --from-index');
    process.exit(1);
  }

  const rows = [['response_id', 'slot', 'original_filename', 'ext', 'typeform_hash', 'expected_bucket']];
  for (const r of parseCsv(fs.readFileSync(PATHS.sourceCsv, 'utf8')).slice(1)) {
    const id = r[COL.responseId];
    for (const { slot, col } of SLOTS) {
      const url = (r[col] || '').trim();
      if (!url) continue;
      const name = basename(url);
      const ext = path.extname(name).toLowerCase();
      rows.push([id, slot, name, ext, typeformHash(url), bucketForExt(ext) || 'QUARANTINE']);
    }
  }
  return rows;
};

// The same rows, read back from the committed file_index.csv. Row order is
// preserved on write, so the batch plan comes out identical either way.
const indexFromFile = () => {
  if (!fs.existsSync(PATHS.fileIndex)) {
    console.error(`file_index.csv not found at ${PATHS.fileIndex}`);
    process.exit(1);
  }
  return parseCsv(fs.readFileSync(PATHS.fileIndex, 'utf8'));
};

const renderBatches = (index) => {
  const body = index.slice(1);

  const byResponse = new Map();
  for (const [id, slot, name] of body) {
    if (!byResponse.has(id)) byResponse.set(id, []);
    byResponse.get(id).push({ slot, name });
  }
  const ids = [...byResponse.keys()];

  // Filenames that appear under more than one response: a flat drop cannot say
  // who they belong to.
  const owners = new Map();
  for (const [id, , name] of body) {
    if (!owners.has(name)) owners.set(name, new Set());
    owners.get(name).add(id);
  }
  const crossPerson = [...owners.entries()].filter(([, set]) => set.size > 1);

  // Filenames that fill more than one slot of the SAME response. The export
  // records a distinct upload per slot but only one name, so nothing on this
  // side can say which file is which. The layout has to.
  const crossSlot = [];
  for (const [id, files] of byResponse) {
    const counted = new Map();
    for (const f of files) counted.set(f.name, [...(counted.get(f.name) || []), f.slot]);
    for (const [name, slots] of counted) {
      if (slots.length > 1) crossSlot.push({ id, name, slots });
    }
  }

  const lines = [
    '# Drop order',
    '',
    'Generated by `migration/scripts/build-index.js`. Do not edit by hand.',
    '',
    `${ids.length} responses carry files, ${body.length} files in total, `
      + `${POLICY.batchSize} responses per batch.`,
    '',
    'Drop one batch at a time, one folder per response, named after the response',
    'id:',
    '',
    '```',
    'incoming/{response_id}/{original_filename}     slot read off the filename',
    'incoming/{response_id}/{slot}/{any_filename}   slot read off the folder',
    '```',
    '',
    'A file may also be named after its slot directly (`front.jpeg`). Original',
    'filenames are matched against `file_index.csv`, so leaving them unchanged is',
    'still the safest default. A harness-added prefix such as',
    '`c96b7e754eed-IMG_0488.jpeg` is fine and matches on suffix.',
    '',
  ];

  if (crossSlot.length) {
    lines.push('## Responses whose slots share a filename');
    lines.push('');
    lines.push('The export gives these slots the same original filename, and nothing on');
    lines.push('this side can tell the files apart. Put each one in a `{slot}/` folder,');
    lines.push('or rename each copy to `{slot}.{ext}`. Dropping them flat is held, never');
    lines.push('guessed.');
    lines.push('');
    for (const c of crossSlot) lines.push(`- \`${c.id}\` \`${c.name}\` fills ${c.slots.join(' and ')}`);
    lines.push('');
  }

  if (crossPerson.length) {
    lines.push('## Filenames that appear under more than one response');
    lines.push('');
    lines.push('These cannot be matched on filename alone. The response id folder');
    lines.push('resolves them; a flat drop is held.');
    lines.push('');
    for (const [name, idSet] of crossPerson) lines.push(`- \`${name}\` -> ${[...idSet].join(', ')}`);
    lines.push('');
  }

  for (let i = 0; i < ids.length; i += POLICY.batchSize) {
    const batchNo = Math.floor(i / POLICY.batchSize) + 1;
    lines.push(`## Batch ${String(batchNo).padStart(2, '0')}`);
    lines.push('');
    for (const id of ids.slice(i, i + POLICY.batchSize)) {
      lines.push(`- \`${id}\``);
      for (const f of byResponse.get(id)) lines.push(`  - ${f.slot}: \`${f.name}\``);
    }
    lines.push('');
  }

  return { text: lines.join('\n'), ids, crossPerson, crossSlot };
};

/**
 * Confirm the export on this machine is the one the column map was built
 * against, without writing anything.
 *
 * The transform addresses columns by position, because Typeform repeats header
 * labels. A re-export with columns in a different order would therefore read
 * plausible values out of the wrong fields and import silent nonsense. Rebuilding
 * the index and comparing it to the committed one catches that: the 200 file
 * references it produces are a fingerprint of the whole layout.
 */
const checkSource = () => {
  const built = indexFromSource().map(r => r.join('|'));
  const committed = indexFromFile().map(r => r.join('|'));

  if (built.length === committed.length && built.every((r, i) => r === committed[i])) {
    console.log(`The export matches. ${built.length - 1} files across `
      + `${new Set(indexFromFile().slice(1).map(r => r[0])).size} responses, all as expected.`);
    return 0;
  }

  console.log('This export does NOT match the one the migration was built against.\n');
  console.log(`  expected ${committed.length - 1} file references, this file gives ${built.length - 1}`);

  const missing = committed.filter(r => !built.includes(r)).slice(1, 6);
  const extra = built.filter(r => !committed.includes(r)).slice(0, 5);
  for (const m of missing) console.log(`  expected but not found:  ${m.split('|').slice(0, 3).join('  ')}`);
  for (const e of extra) console.log(`  found but not expected:  ${e.split('|').slice(0, 3).join('  ')}`);

  console.log('\nDo not import from this file. Columns read by position, so a different');
  console.log('layout would write real-looking values into the wrong fields. Find the');
  console.log('original export, or say so and the column map can be rebuilt for this one.');
  return 4;
};

const main = () => {
  if (process.argv.includes('--check')) process.exit(checkSource());

  const fromIndex = process.argv.includes('--from-index');
  const index = fromIndex ? indexFromFile() : indexFromSource();

  if (!fromIndex) fs.writeFileSync(PATHS.fileIndex, toCsv(index));

  const { text, ids, crossPerson, crossSlot } = renderBatches(index);
  fs.writeFileSync(PATHS.batches, text);

  if (fromIndex) {
    console.log(`file_index.csv  read ${index.length - 1} files (unchanged)`);
  } else {
    console.log(`file_index.csv  ${index.length - 1} files across ${ids.length} responses`);
  }
  console.log(`batches.md      ${Math.ceil(ids.length / POLICY.batchSize)} batches`);
  if (crossPerson.length) {
    console.log(`ambiguous       ${crossPerson.length} filenames span more than one response`);
  }
  if (crossSlot.length) {
    console.log(`ambiguous       ${crossSlot.length} filenames fill two slots of one response`);
  }
};

main();
