/**
 * build-index.js
 *
 * Reads the raw Typeform export and writes two artefacts that the rest of the
 * migration depends on:
 *
 *   migration/file_index.csv  one row per uploaded file (200 rows), recording
 *                             which response and which slot each ORIGINAL
 *                             filename belongs to. This is the lookup table
 *                             that makes a dropped file self-identifying.
 *   migration/batches.md      the drop order, batch by batch.
 *
 * Neither artefact contains contact details or dates of birth. Filenames are
 * included because they are the join key.
 *
 * Usage:  SOURCE_CSV=/path/to/responses.csv node migration/scripts/build-index.js
 */

const fs = require('fs');
const path = require('path');
const { parseCsv, toCsv } = require('./csv');
const { PATHS, COL, SLOTS, bucketForExt, POLICY } = require('./config');

const basename = (url) => (url || '').trim().split('/').pop() || '';

// The hash segment of a Typeform file URL. Unique across all 200 files, so it
// doubles as a stable identifier when a filename is ambiguous.
const typeformHash = (url) => {
  const m = (url || '').match(/\/responses\/files\/([0-9a-f]+)\//);
  return m ? m[1] : '';
};

const main = () => {
  if (!fs.existsSync(PATHS.sourceCsv)) {
    console.error(`Source CSV not found at ${PATHS.sourceCsv}`);
    console.error('Pass it explicitly:  SOURCE_CSV=/path/to/responses.csv node migration/scripts/build-index.js');
    process.exit(1);
  }

  const rows = parseCsv(fs.readFileSync(PATHS.sourceCsv, 'utf8'));
  const data = rows.slice(1);

  const index = [['response_id', 'slot', 'original_filename', 'ext', 'typeform_hash', 'expected_bucket']];
  const byResponse = new Map();

  for (const r of data) {
    const id = r[COL.responseId];
    for (const { slot, col } of SLOTS) {
      const url = (r[col] || '').trim();
      if (!url) continue;

      const name = basename(url);
      const ext = path.extname(name).toLowerCase();
      index.push([id, slot, name, ext, typeformHash(url), bucketForExt(ext) || 'QUARANTINE']);

      if (!byResponse.has(id)) byResponse.set(id, []);
      byResponse.get(id).push({ slot, name });
    }
  }

  fs.writeFileSync(PATHS.fileIndex, toCsv(index));

  // ── Flag filenames that cannot identify a response on their own ─────────────
  const seen = new Map();
  for (const row of index.slice(1)) {
    const [id, , name] = row;
    if (!seen.has(name)) seen.set(name, new Set());
    seen.get(name).add(id);
  }
  const crossPerson = [...seen.entries()].filter(([, ids]) => ids.size > 1);

  // ── Batch plan ──────────────────────────────────────────────────────────────
  const ids = [...byResponse.keys()];
  const lines = [
    '# Drop order',
    '',
    'Generated by `migration/scripts/build-index.js`. Do not edit by hand.',
    '',
    `${ids.length} responses carry files, ${index.length - 1} files in total, `
      + `${POLICY.batchSize} responses per batch.`,
    '',
    'Drop the files for one batch **with their original filenames unchanged**.',
    'Renaming is done on this side; the original name is what makes the file',
    'self-identifying against `file_index.csv`.',
    '',
  ];

  if (crossPerson.length) {
    lines.push('## Filenames that appear under more than one response');
    lines.push('');
    lines.push('These cannot be matched on filename alone. Say which response each');
    lines.push('one belongs to when you drop it, or drop them in separate batches.');
    lines.push('');
    for (const [name, idSet] of crossPerson) lines.push(`- \`${name}\` -> ${[...idSet].join(', ')}`);
    lines.push('');
  }

  for (let i = 0; i < ids.length; i += POLICY.batchSize) {
    const batchNo = Math.floor(i / POLICY.batchSize) + 1;
    lines.push(`## Batch ${String(batchNo).padStart(2, '0')}`);
    lines.push('');
    for (const id of ids.slice(i, i + POLICY.batchSize)) {
      lines.push(`- \`${id}\``);
      for (const f of byResponse.get(id)) lines.push(`  - ${f.slot}: \`${f.name}\``);
    }
    lines.push('');
  }

  fs.writeFileSync(PATHS.batches, lines.join('\n'));

  console.log(`file_index.csv  ${index.length - 1} files across ${ids.length} responses`);
  console.log(`batches.md      ${Math.ceil(ids.length / POLICY.batchSize)} batches`);
  if (crossPerson.length) {
    console.log(`ambiguous       ${crossPerson.length} filenames span more than one response`);
  }
};

main();
